/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2023-03-20 15:08:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/user/Documents/Server%20Programming%20Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Spring_Motorcycle_BBS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1678169223423L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-md-8 mx-auto\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<div class=\"card-header bg-primary pt-3\">\r\n");
      out.write("					<h3 class=\"text-white font-weight-bold\">회원가입</h3>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("						<form id=\"joinForm\" class=\"form-horizontal\" method=\"post\">\r\n");
      out.write("							<div class=\"col-md-10 mx-auto\">\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"userId\" class=\"control-label\">아이디</label>\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"userId\" id=\"userId\" placeholder=\"아이디\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("											<label for=\"userPw\" class=\"control-label\">비밀번호</label>\r\n");
      out.write("											<input type=\"password\" class=\"form-control\" name=\"userPw\" id=\"userPw\" placeholder=\"비밀번호\" required>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("											<label for=\"pw2\" class=\"control-label\">비밀번호 확인</label>\r\n");
      out.write("											<input type=\"password\" class=\"form-control\" name=\"userPw2\" id=\"userPw2\" placeholder=\"비밀번호 확인\" required>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>															\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"userName\" class=\"control-label\">이름</label>\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"userName\" id=\"userName\" placeholder=\"이름\" required>\r\n");
      out.write("								</div>									\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"userEmail\" class=\"control-label\">이메일</label>\r\n");
      out.write("									<input type=\"email\" class=\"form-control\" name=\"userEmail\" id=\"userEmail\" placeholder=\"이메일\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-lg btn-primary float-right\">회원가입</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/script.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <script>\r\n");
      out.write("	 	// Ajax Form 전송\r\n");
      out.write("	    $(\"#joinForm\").submit(function(){		    \r\n");
      out.write("	    	// 비밀번호 동일한지 확인\r\n");
      out.write("			var userPw = $(this).find(\"#userPw\").val();\r\n");
      out.write("			var userPw2 = $(this).find(\"#userPw2\").val();\r\n");
      out.write("\r\n");
      out.write("			if(userPw != userPw2){\r\n");
      out.write("				alert(\"비밀번호를 다시 확인해주세요.\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		    // Ajax 통신\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            type : \"POST\",\r\n");
      out.write("	            url : \"/join\",\r\n");
      out.write("	            data : $(\"#joinForm\").serialize(),\r\n");
      out.write("	            cache : false,\r\n");
      out.write("	            success : function(response){\r\n");
      out.write("	                if(response.overlapIdCheck){\r\n");
      out.write("	                    alert(\"이미 존재하는 아이디입니다. \\n다른 아이디를 사용해주세요.\");\r\n");
      out.write("	                    return false;\r\n");
      out.write("	                 }\r\n");
      out.write("	\r\n");
      out.write("	                 if(response.validPwCheck){\r\n");
      out.write("	                    alert(\"비밀번호를 다시 확인해주세요.\");\r\n");
      out.write("	                    return false;\r\n");
      out.write("	                 }\r\n");
      out.write("	\r\n");
      out.write("	                alert(\"회원가입이 완료되었습니다.\");\r\n");
      out.write("	                 link(\"/\");\r\n");
      out.write("	             }\r\n");
      out.write("	         });\r\n");
      out.write("	\r\n");
      out.write("	         return false;\r\n");
      out.write("	    });\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
